version: "3.8"

services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - mongo  # ensure MongoDB starts before Flask
    environment:
      - FLASK_ENV=development
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - flask-app # ensure flask_app starts before nginx

  mongo:
    image: mongo:8.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - bop_data:/data/db

volumes:
  bop_data:
