version: "3.8"

services:
  flask_app:
    build: .
    container_name: flask_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongo  # ensure MongoDB starts before Flask
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app

  mongo:
    image: mongo:8.0
    container_name: mongo
    restart: unless-stopped
    command: mongod --auth
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    env_file:
      - .env
    volumes:
      - bop_data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask_app # ensure flask_app starts before nginx
    volumes:
      - ./nginx/bop-dropper.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  bop_data:
