version: "3.8"

services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - mongo  # ensure MongoDB starts before Flask
    environment:
      - FLASK_ENV=development
    env_file:
      - .env

  mongo:
    image: mongo:8.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - bop_data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - flask_app # ensure flask_app starts before nginx
    volumes:
      - ./nginx/bop-dropper.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/letsencrypt

volumes:
  bop_data:
